/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Oct  9 14:47:19 2017. */

#ifndef PB_POSITIONING_PB_H_INCLUDED
#define PB_POSITIONING_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _PositioningSystem {
     SYSTEM_GPS = 0,
     SYSTEM_BDS = 1,
     SYSTEM_GAL = 2,
     SYSTEM_GLO = 3,
     SYSTEM_COUNT = 4,
     SYSTEM_USING_EPH_TYPE1_COUNT = 3,
     SYSTEM_USING_EPH_TYPE2_COUNT = 1
} PositioningSystem;
#define _ MIN  SYSTEM_GPS
#define _ MAX  SYSTEM_USING_EPH_TYPE2_COUNT
#define _ ARRAYSIZE ((PositioningSystem)( SYSTEM_USING_EPH_TYPE2_COUNT+1))

typedef enum _PositioningCommonInfo {
     PositioningCommonInfo_default = 0,
     GPS_SV_COUNT = 32,
     GPS_MIN_SVID = 1,
     GPS_MAX_SVID = 32,
     BDS_SV_COUNT = 35,
     BDS_GEO_SV_COUNT = 5,
     BDS_MIN_SVID = 41,
     BDS_MAX_SVID = 75,
     BDS_GEO_MAX_SVID = 45,
     GAL_SV_COUNT = 30,
     GAL_MIN_SVID = 81,
     GAL_MAX_SVID = 110,
     GLO_SV_COUNT = 26,
     GLO_MIN_SVID = 131,
     GLO_MAX_SVID = 156
} PositioningCommonInfo;
#define _ MIN   PositioningCommonInfo_default
#define _ MAX  GLO_MAX_SVID
#define _ ARRAYSIZE ((PositioningCommonInfo)( GLO_MAX_SVID+1))

typedef enum _PositioningIonoParamFlag {
     PositioningIonoParamFlag_default = 0,
     IONO_PARAM_ALPHA0_VALID = 1,
     IONO_PARAM_ALPHA1_VALID = 2,
     IONO_PARAM_ALPHA2_VALID = 4,
     IONO_PARAM_ALPHA3_VALID = 8,
     IONO_PARAM_BETA0_VALID = 16,
     IONO_PARAM_BETA1_VALID = 32,
     IONO_PARAM_BETA2_VALID = 64,
     IONO_PARAM_BETA3_VALID = 128,
     IONO_PARAM_ALL_VALID = 255
} PositioningIonoParamFlag;
#define _ MIN   PositioningIonoParamFlag_default
#define _ MAX  IONO_PARAM_ALL_VALID
#define _ ARRAYSIZE ((PositioningIonoParamFlag)( IONO_PARAM_ALL_VALID+1))

typedef enum _PositioningUtcParamFlag {
     PositioningUtcParamFlag_default = 0,
     UTC_PARAM_DELTA_TLS_VALID = 1,
     UTC_PARAM_DELTA_TLSF_VALID = 2,
     UTC_PARAM_DN_VALID = 4,
     UTC_PARAM_WNT_VALID = 8,
     UTC_PARAM_WNLSF_VALID = 16,
     UTC_PARAM_TOT_VALID = 32,
     UTC_PARAM_A0_VALID = 64,
     UTC_PARAM_A1_VALID = 128,
     UTC_PARAM_ALL_VALID = 255
} PositioningUtcParamFlag;
#define _ MIN   default
#define _ MAX  UTC_PARAM_ALL_VALID
#define _ ARRAYSIZE ((PositioningUtcParamFlag)( UTC_PARAM_ALL_VALID+1))

typedef enum _PositioningTimeAccuracyType {
    PositioningTimeAccuracyType_FULL_TIME_IS_ACCURATE = 0,
    PositioningTimeAccuracyType_SUB_20MS_TIME_IS_ACCURATE = 1,
    PositioningTimeAccuracyType_SUB_1MS_TIME_IS_ACCURATE = 2
} PositioningTimeAccuracyType;
#define _PositioningTimeAccuracyType_MIN PositioningTimeAccuracyType_FULL_TIME_IS_ACCURATE
#define _PositioningTimeAccuracyType_MAX PositioningTimeAccuracyType_SUB_1MS_TIME_IS_ACCURATE
#define _PositioningTimeAccuracyType_ARRAYSIZE ((PositioningTimeAccuracyType)(PositioningTimeAccuracyType_SUB_1MS_TIME_IS_ACCURATE+1))

/* Struct definitions */
typedef struct _PositioningHMatrix {
    pb_callback_t sat_count;
    pb_callback_t value;
    pb_callback_t weight;
/* @@protoc_insertion_point(struct:PositioningHMatrix) */
} PositioningHMatrix;

typedef struct _PositioningAlmanac {
    int32_t flag;
    int32_t svid;
    int32_t health;
    int32_t flag2;
    int32_t week;
    int32_t toa;
    int32_t reserved;
    double sqrt_a;
    double e;
    double i0;
    double omega0;
    double w;
    double M0;
    double omega_dot;
    double af0;
    double af1;
    double a;
    double ae;
    double n;
    double sqrt_1me2;
    double omega_temp;
    double delta_omega;
/* @@protoc_insertion_point(struct:PositioningAlmanac) */
} PositioningAlmanac;

typedef struct _PositioningCachedPvaAndEa {
    int32_t flag;
    int32_t svid;
    uint32_t reserved;
    int32_t toe;
    pb_callback_t sec_time;
    pb_callback_t pva;
    pb_callback_t ea;
/* @@protoc_insertion_point(struct:PositioningCachedPvaAndEa) */
} PositioningCachedPvaAndEa;

typedef struct _PositioningEccentricAnomaly {
    double Ek;
    double Ek_dot;
/* @@protoc_insertion_point(struct:PositioningEccentricAnomaly) */
} PositioningEccentricAnomaly;

typedef struct _PositioningElAz {
    double el;
    double az;
/* @@protoc_insertion_point(struct:PositioningElAz) */
} PositioningElAz;

typedef struct _PositioningEphemerisType1 {
    int32_t flag;
    int32_t svid;
    int32_t health;
    int32_t ura;
    int32_t week;
    int32_t toe;
    int32_t toc;
    double sqrt_a;
    double e;
    double i0;
    double omega0;
    double w;
    double M0;
    double omega_dot;
    double af0;
    double af1;
    double a;
    double ae;
    double sqrt_1me2;
    double n;
    double omega_temp;
    double delta_omega;
    double delta_n;
    double i_dot;
    double cuc;
    double cus;
    double crc;
    double crs;
    double cic;
    double cis;
    double af2;
    double tgd;
    double tgd2;
/* @@protoc_insertion_point(struct:PositioningEphemerisType1) */
} PositioningEphemerisType1;

typedef struct _PositioningEphemerisType2 {
    int32_t flag;
    int32_t svid;
    int32_t health;
    int32_t reserved;
    int32_t tb;
    double tau;
    double gamma;
    double x;
    double y;
    double z;
    double vx;
    double vy;
    double vz;
    double ax;
    double ay;
    double az;
/* @@protoc_insertion_point(struct:PositioningEphemerisType2) */
} PositioningEphemerisType2;

typedef struct _PositioningIonoParam {
    int32_t flag;
    float alpha0;
    float alpha1;
    float alpha2;
    float alpha3;
    float beta0;
    float beta1;
    float beta2;
    float beta3;
/* @@protoc_insertion_point(struct:PositioningIonoParam) */
} PositioningIonoParam;

typedef struct _PositioningLatLonAlt {
    double lat;
    double lon;
    double alt;
/* @@protoc_insertion_point(struct:PositioningLatLonAlt) */
} PositioningLatLonAlt;

typedef struct _PositioningMeasurement {
    int32_t sys;
    int32_t svid;
    uint32_t cn0;
    int32_t transmit_time_integer_part;
    double transmit_time_fraction_part;
    double doppler;
/* @@protoc_insertion_point(struct:PositioningMeasurement) */
} PositioningMeasurement;

typedef struct _PositioningPos {
    double x;
    double y;
    double z;
/* @@protoc_insertion_point(struct:PositioningPos) */
} PositioningPos;

typedef struct _PositioningPvtBuffer {
    pb_callback_t state_vector;
    PositioningHMatrix h_matrix;
    pb_callback_t delta_msr;
    pb_callback_t temp_matrix;
    pb_callback_t temp_vector;
/* @@protoc_insertion_point(struct:PositioningPvtBuffer) */
} PositioningPvtBuffer;

typedef struct _PositioningUtcParam {
    int32_t flag;
    int32_t delta_tLS;
    int32_t delta_tLSF;
    int32_t DN;
    uint32_t WNt;
    uint32_t WNLSF;
    uint32_t tot;
    double A0;
    double A1;
/* @@protoc_insertion_point(struct:PositioningUtcParam) */
} PositioningUtcParam;

typedef struct _PositioningUtcTime {
    int32_t year;
    int32_t month;
    int32_t day;
    int32_t hour;
    int32_t minute;
    int32_t second;
    int32_t millisecond;
/* @@protoc_insertion_point(struct:PositioningUtcTime) */
} PositioningUtcTime;

typedef struct _PositioningNavMessage {
    pb_callback_t eph_type1;
    pb_callback_t eph_type2;
    pb_callback_t alm;
    PositioningIonoParam iono_param;
    PositioningUtcParam utc_param;
/* @@protoc_insertion_point(struct:PositioningNavMessage) */
} PositioningNavMessage;

typedef struct _PositioningPosVel {
    PositioningPos p;
    double vx;
    double vy;
    double vz;
/* @@protoc_insertion_point(struct:PositioningPosVel) */
} PositioningPosVel;

typedef struct _PositioningCachedPv {
    int32_t flag;
    int32_t svid;
    uint32_t reserved;
    int32_t tb;
    double sec_time;
    PositioningPosVel pv;
/* @@protoc_insertion_point(struct:PositioningCachedPv) */
} PositioningCachedPv;

typedef struct _PositioningPosVelAcc {
    PositioningPosVel pv;
    double ax;
    double ay;
    double az;
/* @@protoc_insertion_point(struct:PositioningPosVelAcc) */
} PositioningPosVelAcc;

typedef struct _PositioningReceiverInfo {
    PositioningPosVel pv;
    PositioningLatLonAlt lla;
    pb_callback_t receiver_time_integer_part;
    pb_callback_t receiver_time_fraction_part;
    double clock_drift;
/* @@protoc_insertion_point(struct:PositioningReceiverInfo) */
} PositioningReceiverInfo;

typedef struct _PositioningSatInfo {
    double sat_clock_err;
    PositioningPosVel pv;
    double Ek;
    PositioningElAz el_az;
    double pseudo_range_corr;
/* @@protoc_insertion_point(struct:PositioningSatInfo) */
} PositioningSatInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PositioningUtcTime_init_default          {0, 0, 0, 0, 0, 0, 0}
#define PositioningPos_init_default              {0, 0, 0}
#define PositioningPosVel_init_default           {PositioningPos_init_default, 0, 0, 0}
#define PositioningPosVelAcc_init_default        {PositioningPosVel_init_default, 0, 0, 0}
#define PositioningLatLonAlt_init_default        {0, 0, 0}
#define PositioningEccentricAnomaly_init_default {0, 0}
#define PositioningEphemerisType1_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningEphemerisType2_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningAlmanac_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningIonoParam_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningUtcParam_init_default         {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningNavMessage_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, PositioningIonoParam_init_default, PositioningUtcParam_init_default}
#define PositioningReceiverInfo_init_default     {PositioningPosVel_init_default, PositioningLatLonAlt_init_default, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define PositioningCachedPvaAndEa_init_default   {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PositioningCachedPv_init_default         {0, 0, 0, 0, 0, PositioningPosVel_init_default}
#define PositioningMeasurement_init_default      {0, 0, 0, 0, 0, 0}
#define PositioningElAz_init_default             {0, 0}
#define PositioningSatInfo_init_default          {0, PositioningPosVel_init_default, 0, PositioningElAz_init_default, 0}
#define PositioningHMatrix_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PositioningPvtBuffer_init_default        {{{NULL}, NULL}, PositioningHMatrix_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PositioningUtcTime_init_zero             {0, 0, 0, 0, 0, 0, 0}
#define PositioningPos_init_zero                 {0, 0, 0}
#define PositioningPosVel_init_zero              {PositioningPos_init_zero, 0, 0, 0}
#define PositioningPosVelAcc_init_zero           {PositioningPosVel_init_zero, 0, 0, 0}
#define PositioningLatLonAlt_init_zero           {0, 0, 0}
#define PositioningEccentricAnomaly_init_zero    {0, 0}
#define PositioningEphemerisType1_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningEphemerisType2_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningAlmanac_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningIonoParam_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningUtcParam_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PositioningNavMessage_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, PositioningIonoParam_init_zero, PositioningUtcParam_init_zero}
#define PositioningReceiverInfo_init_zero        {PositioningPosVel_init_zero, PositioningLatLonAlt_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define PositioningCachedPvaAndEa_init_zero      {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PositioningCachedPv_init_zero            {0, 0, 0, 0, 0, PositioningPosVel_init_zero}
#define PositioningMeasurement_init_zero         {0, 0, 0, 0, 0, 0}
#define PositioningElAz_init_zero                {0, 0}
#define PositioningSatInfo_init_zero             {0, PositioningPosVel_init_zero, 0, PositioningElAz_init_zero, 0}
#define PositioningHMatrix_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PositioningPvtBuffer_init_zero           {{{NULL}, NULL}, PositioningHMatrix_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define PositioningHMatrix_sat_count_tag         1
#define PositioningHMatrix_value_tag             2
#define PositioningHMatrix_weight_tag            3
#define PositioningAlmanac_flag_tag              1
#define PositioningAlmanac_svid_tag              2
#define PositioningAlmanac_health_tag            3
#define PositioningAlmanac_flag2_tag             4
#define PositioningAlmanac_week_tag              5
#define PositioningAlmanac_toa_tag               6
#define PositioningAlmanac_reserved_tag          7
#define PositioningAlmanac_sqrt_a_tag            8
#define PositioningAlmanac_e_tag                 9
#define PositioningAlmanac_i0_tag                10
#define PositioningAlmanac_omega0_tag            11
#define PositioningAlmanac_w_tag                 12
#define PositioningAlmanac_M0_tag                13
#define PositioningAlmanac_omega_dot_tag         14
#define PositioningAlmanac_af0_tag               15
#define PositioningAlmanac_af1_tag               16
#define PositioningAlmanac_a_tag                 17
#define PositioningAlmanac_ae_tag                18
#define PositioningAlmanac_n_tag                 19
#define PositioningAlmanac_sqrt_1me2_tag         20
#define PositioningAlmanac_omega_temp_tag        21
#define PositioningAlmanac_delta_omega_tag       22
#define PositioningCachedPvaAndEa_flag_tag       1
#define PositioningCachedPvaAndEa_svid_tag       2
#define PositioningCachedPvaAndEa_reserved_tag   3
#define PositioningCachedPvaAndEa_toe_tag        4
#define PositioningCachedPvaAndEa_sec_time_tag   5
#define PositioningCachedPvaAndEa_pva_tag        6
#define PositioningCachedPvaAndEa_ea_tag         7
#define PositioningEccentricAnomaly_Ek_tag       1
#define PositioningEccentricAnomaly_Ek_dot_tag   2
#define PositioningElAz_el_tag                   1
#define PositioningElAz_az_tag                   2
#define PositioningEphemerisType1_flag_tag       1
#define PositioningEphemerisType1_svid_tag       2
#define PositioningEphemerisType1_health_tag     3
#define PositioningEphemerisType1_ura_tag        4
#define PositioningEphemerisType1_week_tag       5
#define PositioningEphemerisType1_toe_tag        6
#define PositioningEphemerisType1_toc_tag        7
#define PositioningEphemerisType1_sqrt_a_tag     8
#define PositioningEphemerisType1_e_tag          9
#define PositioningEphemerisType1_i0_tag         10
#define PositioningEphemerisType1_omega0_tag     11
#define PositioningEphemerisType1_w_tag          12
#define PositioningEphemerisType1_M0_tag         13
#define PositioningEphemerisType1_omega_dot_tag  14
#define PositioningEphemerisType1_af0_tag        15
#define PositioningEphemerisType1_af1_tag        16
#define PositioningEphemerisType1_a_tag          17
#define PositioningEphemerisType1_ae_tag         18
#define PositioningEphemerisType1_sqrt_1me2_tag  19
#define PositioningEphemerisType1_n_tag          20
#define PositioningEphemerisType1_omega_temp_tag 21
#define PositioningEphemerisType1_delta_omega_tag 22
#define PositioningEphemerisType1_delta_n_tag    23
#define PositioningEphemerisType1_i_dot_tag      24
#define PositioningEphemerisType1_cuc_tag        25
#define PositioningEphemerisType1_cus_tag        26
#define PositioningEphemerisType1_crc_tag        27
#define PositioningEphemerisType1_crs_tag        28
#define PositioningEphemerisType1_cic_tag        29
#define PositioningEphemerisType1_cis_tag        30
#define PositioningEphemerisType1_af2_tag        31
#define PositioningEphemerisType1_tgd_tag        32
#define PositioningEphemerisType1_tgd2_tag       33
#define PositioningEphemerisType2_flag_tag       1
#define PositioningEphemerisType2_svid_tag       2
#define PositioningEphemerisType2_health_tag     3
#define PositioningEphemerisType2_reserved_tag   4
#define PositioningEphemerisType2_tb_tag         5
#define PositioningEphemerisType2_tau_tag        6
#define PositioningEphemerisType2_gamma_tag      7
#define PositioningEphemerisType2_x_tag          8
#define PositioningEphemerisType2_y_tag          9
#define PositioningEphemerisType2_z_tag          10
#define PositioningEphemerisType2_vx_tag         11
#define PositioningEphemerisType2_vy_tag         12
#define PositioningEphemerisType2_vz_tag         13
#define PositioningEphemerisType2_ax_tag         14
#define PositioningEphemerisType2_ay_tag         15
#define PositioningEphemerisType2_az_tag         16
#define PositioningIonoParam_flag_tag            1
#define PositioningIonoParam_alpha0_tag          2
#define PositioningIonoParam_alpha1_tag          3
#define PositioningIonoParam_alpha2_tag          4
#define PositioningIonoParam_alpha3_tag          5
#define PositioningIonoParam_beta0_tag           6
#define PositioningIonoParam_beta1_tag           7
#define PositioningIonoParam_beta2_tag           8
#define PositioningIonoParam_beta3_tag           9
#define PositioningLatLonAlt_lat_tag             1
#define PositioningLatLonAlt_lon_tag             2
#define PositioningLatLonAlt_alt_tag             3
#define PositioningMeasurement_sys_tag           1
#define PositioningMeasurement_svid_tag          2
#define PositioningMeasurement_cn0_tag           3
#define PositioningMeasurement_transmit_time_integer_part_tag 4
#define PositioningMeasurement_transmit_time_fraction_part_tag 5
#define PositioningMeasurement_doppler_tag       6
#define PositioningPos_x_tag                     1
#define PositioningPos_y_tag                     2
#define PositioningPos_z_tag                     3
#define PositioningPvtBuffer_state_vector_tag    1
#define PositioningPvtBuffer_h_matrix_tag        2
#define PositioningPvtBuffer_delta_msr_tag       3
#define PositioningPvtBuffer_temp_matrix_tag     4
#define PositioningPvtBuffer_temp_vector_tag     5
#define PositioningUtcParam_flag_tag             1
#define PositioningUtcParam_delta_tLS_tag        2
#define PositioningUtcParam_delta_tLSF_tag       3
#define PositioningUtcParam_DN_tag               4
#define PositioningUtcParam_WNt_tag              5
#define PositioningUtcParam_WNLSF_tag            6
#define PositioningUtcParam_tot_tag              7
#define PositioningUtcParam_A0_tag               8
#define PositioningUtcParam_A1_tag               9
#define PositioningUtcTime_year_tag              1
#define PositioningUtcTime_month_tag             2
#define PositioningUtcTime_day_tag               3
#define PositioningUtcTime_hour_tag              4
#define PositioningUtcTime_minute_tag            5
#define PositioningUtcTime_second_tag            6
#define PositioningUtcTime_millisecond_tag       7
#define PositioningNavMessage_eph_type1_tag      1
#define PositioningNavMessage_eph_type2_tag      2
#define PositioningNavMessage_alm_tag            3
#define PositioningNavMessage_iono_param_tag     4
#define PositioningNavMessage_utc_param_tag      5
#define PositioningPosVel_p_tag                  1
#define PositioningPosVel_vx_tag                 2
#define PositioningPosVel_vy_tag                 3
#define PositioningPosVel_vz_tag                 4
#define PositioningCachedPv_flag_tag             1
#define PositioningCachedPv_svid_tag             2
#define PositioningCachedPv_reserved_tag         3
#define PositioningCachedPv_tb_tag               4
#define PositioningCachedPv_sec_time_tag         5
#define PositioningCachedPv_pv_tag               6
#define PositioningPosVelAcc_pv_tag              1
#define PositioningPosVelAcc_ax_tag              2
#define PositioningPosVelAcc_ay_tag              3
#define PositioningPosVelAcc_az_tag              4
#define PositioningReceiverInfo_pv_tag           1
#define PositioningReceiverInfo_lla_tag          2
#define PositioningReceiverInfo_receiver_time_integer_part_tag 3
#define PositioningReceiverInfo_receiver_time_fraction_part_tag 4
#define PositioningReceiverInfo_clock_drift_tag  5
#define PositioningSatInfo_sat_clock_err_tag     1
#define PositioningSatInfo_pv_tag                2
#define PositioningSatInfo_Ek_tag                3
#define PositioningSatInfo_el_az_tag             4
#define PositioningSatInfo_pseudo_range_corr_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t PositioningUtcTime_fields[8];
extern const pb_field_t PositioningPos_fields[4];
extern const pb_field_t PositioningPosVel_fields[5];
extern const pb_field_t PositioningPosVelAcc_fields[5];
extern const pb_field_t PositioningLatLonAlt_fields[4];
extern const pb_field_t PositioningEccentricAnomaly_fields[3];
extern const pb_field_t PositioningEphemerisType1_fields[34];
extern const pb_field_t PositioningEphemerisType2_fields[17];
extern const pb_field_t PositioningAlmanac_fields[23];
extern const pb_field_t PositioningIonoParam_fields[10];
extern const pb_field_t PositioningUtcParam_fields[10];
extern const pb_field_t PositioningNavMessage_fields[6];
extern const pb_field_t PositioningReceiverInfo_fields[6];
extern const pb_field_t PositioningCachedPvaAndEa_fields[8];
extern const pb_field_t PositioningCachedPv_fields[7];
extern const pb_field_t PositioningMeasurement_fields[7];
extern const pb_field_t PositioningElAz_fields[3];
extern const pb_field_t PositioningSatInfo_fields[6];
extern const pb_field_t PositioningHMatrix_fields[4];
extern const pb_field_t PositioningPvtBuffer_fields[6];

/* Maximum encoded size of messages (where known) */
#define PositioningUtcTime_size                  77
#define PositioningPos_size                      27
#define PositioningPosVel_size                   56
#define PositioningPosVelAcc_size                85
#define PositioningLatLonAlt_size                27
#define PositioningEccentricAnomaly_size         18
#define PositioningEphemerisType1_size           329
#define PositioningEphemerisType2_size           155
#define PositioningAlmanac_size                  219
#define PositioningIonoParam_size                51
#define PositioningUtcParam_size                 80
/* PositioningNavMessage_size depends on runtime parameters */
/* PositioningReceiverInfo_size depends on runtime parameters */
/* PositioningCachedPvaAndEa_size depends on runtime parameters */
#define PositioningCachedPv_size                 106
#define PositioningMeasurement_size              57
#define PositioningElAz_size                     18
#define PositioningSatInfo_size                  105
/* PositioningHMatrix_size depends on runtime parameters */
/* PositioningPvtBuffer_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define POSITIONING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
