/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Oct  9 14:47:19 2017. */

#include "positioning.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PositioningUtcTime_fields[8] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningUtcTime, year, year, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcTime, month, year, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcTime, day, month, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcTime, hour, day, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcTime, minute, hour, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcTime, second, minute, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcTime, millisecond, second, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningPos_fields[4] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningPos, x, x, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPos, y, x, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPos, z, y, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningPosVel_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, PositioningPosVel, p, p, &PositioningPos_fields),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosVel, vx, p, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosVel, vy, vx, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosVel, vz, vy, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningPosVelAcc_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, PositioningPosVelAcc, pv, pv, &PositioningPosVel_fields),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosVelAcc, ax, pv, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosVelAcc, ay, ax, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosVelAcc, az, ay, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningLatLonAlt_fields[4] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningLatLonAlt, lat, lat, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningLatLonAlt, lon, lat, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningLatLonAlt, alt, lon, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningEccentricAnomaly_fields[3] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningEccentricAnomaly, Ek, Ek, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEccentricAnomaly, Ek_dot, Ek, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningEphemerisType1_fields[34] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningEphemerisType1, flag, flag, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, svid, flag, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, health, svid, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, ura, health, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, week, ura, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, toe, week, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, toc, toe, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, sqrt_a, toc, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, e, sqrt_a, 0),
    PB_FIELD( 10, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, i0, e, 0),
    PB_FIELD( 11, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, omega0, i0, 0),
    PB_FIELD( 12, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, w, omega0, 0),
    PB_FIELD( 13, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, M0, w, 0),
    PB_FIELD( 14, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, omega_dot, M0, 0),
    PB_FIELD( 15, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, af0, omega_dot, 0),
    PB_FIELD( 16, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, af1, af0, 0),
    PB_FIELD( 17, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, a, af1, 0),
    PB_FIELD( 18, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, ae, a, 0),
    PB_FIELD( 19, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, sqrt_1me2, ae, 0),
    PB_FIELD( 20, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, n, sqrt_1me2, 0),
    PB_FIELD( 21, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, omega_temp, n, 0),
    PB_FIELD( 22, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, delta_omega, omega_temp, 0),
    PB_FIELD( 23, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, delta_n, delta_omega, 0),
    PB_FIELD( 24, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, i_dot, delta_n, 0),
    PB_FIELD( 25, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, cuc, i_dot, 0),
    PB_FIELD( 26, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, cus, cuc, 0),
    PB_FIELD( 27, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, crc, cus, 0),
    PB_FIELD( 28, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, crs, crc, 0),
    PB_FIELD( 29, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, cic, crs, 0),
    PB_FIELD( 30, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, cis, cic, 0),
    PB_FIELD( 31, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, af2, cis, 0),
    PB_FIELD( 32, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, tgd, af2, 0),
    PB_FIELD( 33, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType1, tgd2, tgd, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningEphemerisType2_fields[17] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningEphemerisType2, flag, flag, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, svid, flag, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, health, svid, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, reserved, health, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, tb, reserved, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, tau, tb, 0),
    PB_FIELD(  7, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, gamma, tau, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, x, gamma, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, y, x, 0),
    PB_FIELD( 10, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, z, y, 0),
    PB_FIELD( 11, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, vx, z, 0),
    PB_FIELD( 12, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, vy, vx, 0),
    PB_FIELD( 13, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, vz, vy, 0),
    PB_FIELD( 14, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, ax, vz, 0),
    PB_FIELD( 15, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, ay, ax, 0),
    PB_FIELD( 16, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningEphemerisType2, az, ay, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningAlmanac_fields[23] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningAlmanac, flag, flag, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningAlmanac, svid, flag, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, PositioningAlmanac, health, svid, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningAlmanac, flag2, health, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, PositioningAlmanac, week, flag2, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, PositioningAlmanac, toa, week, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, PositioningAlmanac, reserved, toa, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, sqrt_a, reserved, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, e, sqrt_a, 0),
    PB_FIELD( 10, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, i0, e, 0),
    PB_FIELD( 11, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, omega0, i0, 0),
    PB_FIELD( 12, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, w, omega0, 0),
    PB_FIELD( 13, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, M0, w, 0),
    PB_FIELD( 14, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, omega_dot, M0, 0),
    PB_FIELD( 15, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, af0, omega_dot, 0),
    PB_FIELD( 16, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, af1, af0, 0),
    PB_FIELD( 17, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, a, af1, 0),
    PB_FIELD( 18, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, ae, a, 0),
    PB_FIELD( 19, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, n, ae, 0),
    PB_FIELD( 20, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, sqrt_1me2, n, 0),
    PB_FIELD( 21, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, omega_temp, sqrt_1me2, 0),
    PB_FIELD( 22, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningAlmanac, delta_omega, omega_temp, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningIonoParam_fields[10] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningIonoParam, flag, flag, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, alpha0, flag, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, alpha1, alpha0, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, alpha2, alpha1, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, alpha3, alpha2, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, beta0, alpha3, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, beta1, beta0, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, beta2, beta1, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, PositioningIonoParam, beta3, beta2, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningUtcParam_fields[10] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningUtcParam, flag, flag, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcParam, delta_tLS, flag, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcParam, delta_tLSF, delta_tLS, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningUtcParam, DN, delta_tLSF, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, PositioningUtcParam, WNt, DN, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, PositioningUtcParam, WNLSF, WNt, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, PositioningUtcParam, tot, WNLSF, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningUtcParam, A0, tot, 0),
    PB_FIELD(  9, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningUtcParam, A1, A0, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningNavMessage_fields[6] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, PositioningNavMessage, eph_type1, eph_type1, &PositioningEphemerisType1_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, PositioningNavMessage, eph_type2, eph_type1, &PositioningEphemerisType2_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, PositioningNavMessage, alm, eph_type2, &PositioningAlmanac_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningNavMessage, iono_param, alm, &PositioningIonoParam_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningNavMessage, utc_param, iono_param, &PositioningUtcParam_fields),
    PB_LAST_FIELD
};

const pb_field_t PositioningReceiverInfo_fields[6] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, PositioningReceiverInfo, pv, pv, &PositioningPosVel_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningReceiverInfo, lla, pv, &PositioningLatLonAlt_fields),
    PB_FIELD(  3, INT32   , REPEATED, CALLBACK, OTHER, PositioningReceiverInfo, receiver_time_integer_part, lla, 0),
    PB_FIELD(  4, DOUBLE  , REPEATED, CALLBACK, OTHER, PositioningReceiverInfo, receiver_time_fraction_part, receiver_time_integer_part, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningReceiverInfo, clock_drift, receiver_time_fraction_part, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningCachedPvaAndEa_fields[8] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningCachedPvaAndEa, flag, flag, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningCachedPvaAndEa, svid, flag, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, PositioningCachedPvaAndEa, reserved, svid, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningCachedPvaAndEa, toe, reserved, 0),
    PB_FIELD(  5, INT32   , REPEATED, CALLBACK, OTHER, PositioningCachedPvaAndEa, sec_time, toe, 0),
    PB_FIELD(  6, MESSAGE , REPEATED, CALLBACK, OTHER, PositioningCachedPvaAndEa, pva, sec_time, &PositioningPosVelAcc_fields),
    PB_FIELD(  7, MESSAGE , REPEATED, CALLBACK, OTHER, PositioningCachedPvaAndEa, ea, pva, &PositioningEccentricAnomaly_fields),
    PB_LAST_FIELD
};

const pb_field_t PositioningCachedPv_fields[7] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningCachedPv, flag, flag, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningCachedPv, svid, flag, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, PositioningCachedPv, reserved, svid, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningCachedPv, tb, reserved, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningCachedPv, sec_time, tb, 0),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningCachedPv, pv, sec_time, &PositioningPosVel_fields),
    PB_LAST_FIELD
};

const pb_field_t PositioningMeasurement_fields[7] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PositioningMeasurement, sys, sys, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PositioningMeasurement, svid, sys, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, PositioningMeasurement, cn0, svid, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, PositioningMeasurement, transmit_time_integer_part, cn0, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningMeasurement, transmit_time_fraction_part, transmit_time_integer_part, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningMeasurement, doppler, transmit_time_fraction_part, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningElAz_fields[3] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningElAz, el, el, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningElAz, az, el, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningSatInfo_fields[6] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningSatInfo, sat_clock_err, sat_clock_err, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningSatInfo, pv, sat_clock_err, &PositioningPosVel_fields),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningSatInfo, Ek, pv, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningSatInfo, el_az, Ek, &PositioningElAz_fields),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningSatInfo, pseudo_range_corr, el_az, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningHMatrix_fields[4] = {
    PB_FIELD(  1, UINT32  , REPEATED, CALLBACK, FIRST, PositioningHMatrix, sat_count, sat_count, 0),
    PB_FIELD(  2, DOUBLE  , REPEATED, CALLBACK, OTHER, PositioningHMatrix, value, sat_count, 0),
    PB_FIELD(  3, DOUBLE  , REPEATED, CALLBACK, OTHER, PositioningHMatrix, weight, value, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningPvtBuffer_fields[6] = {
    PB_FIELD(  1, DOUBLE  , REPEATED, CALLBACK, FIRST, PositioningPvtBuffer, state_vector, state_vector, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningPvtBuffer, h_matrix, state_vector, &PositioningHMatrix_fields),
    PB_FIELD(  3, DOUBLE  , REPEATED, CALLBACK, OTHER, PositioningPvtBuffer, delta_msr, h_matrix, 0),
    PB_FIELD(  4, DOUBLE  , REPEATED, CALLBACK, OTHER, PositioningPvtBuffer, temp_matrix, delta_msr, 0),
    PB_FIELD(  5, DOUBLE  , REPEATED, CALLBACK, OTHER, PositioningPvtBuffer, temp_vector, temp_matrix, 0),
    PB_LAST_FIELD
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PositioningPosVel, p) < 65536 && pb_membersize(PositioningPosVelAcc, pv) < 65536 && pb_membersize(PositioningNavMessage, iono_param) < 65536 && pb_membersize(PositioningNavMessage, utc_param) < 65536 && pb_membersize(PositioningReceiverInfo, pv) < 65536 && pb_membersize(PositioningReceiverInfo, lla) < 65536 && pb_membersize(PositioningCachedPv, pv) < 65536 && pb_membersize(PositioningSatInfo, pv) < 65536 && pb_membersize(PositioningSatInfo, el_az) < 65536 && pb_membersize(PositioningPvtBuffer, h_matrix) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PositioningUtcTime_PositioningPos_PositioningPosVel_PositioningPosVelAcc_PositioningLatLonAlt_PositioningEccentricAnomaly_PositioningEphemerisType1_PositioningEphemerisType2_PositioningAlmanac_PositioningIonoParam_PositioningUtcParam_PositioningNavMessage_PositioningReceiverInfo_PositioningCachedPvaAndEa_PositioningCachedPv_PositioningMeasurement_PositioningElAz_PositioningSatInfo_PositioningHMatrix_PositioningPvtBuffer)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PositioningPosVel, p) < 256 && pb_membersize(PositioningPosVelAcc, pv) < 256 && pb_membersize(PositioningNavMessage, iono_param) < 256 && pb_membersize(PositioningNavMessage, utc_param) < 256 && pb_membersize(PositioningReceiverInfo, pv) < 256 && pb_membersize(PositioningReceiverInfo, lla) < 256 && pb_membersize(PositioningCachedPv, pv) < 256 && pb_membersize(PositioningSatInfo, pv) < 256 && pb_membersize(PositioningSatInfo, el_az) < 256 && pb_membersize(PositioningPvtBuffer, h_matrix) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PositioningUtcTime_PositioningPos_PositioningPosVel_PositioningPosVelAcc_PositioningLatLonAlt_PositioningEccentricAnomaly_PositioningEphemerisType1_PositioningEphemerisType2_PositioningAlmanac_PositioningIonoParam_PositioningUtcParam_PositioningNavMessage_PositioningReceiverInfo_PositioningCachedPvaAndEa_PositioningCachedPv_PositioningMeasurement_PositioningElAz_PositioningSatInfo_PositioningHMatrix_PositioningPvtBuffer)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
