/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Sep 29 15:34:54 2017. */

#include "eph.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t List_GPS_EPHEMERIS_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, List_GPS_EPHEMERIS, items, items, &GPS_EPHEMERIS_fields),
    PB_LAST_FIELD
};

const pb_field_t GPS_EPHEMERIS_fields[37] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, GPS_EPHEMERIS, iodc, iodc, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, iode2, iodc, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, iode3, iode2, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, ura, iode3, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, flag, ura, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, health, flag, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, svid, health, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, toe, svid, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, toc, toe, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, week, toc, 0),
    PB_FIELD( 12, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, M0, week, 0),
    PB_FIELD( 13, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, delta_n, M0, 0),
    PB_FIELD( 14, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, ecc, delta_n, 0),
    PB_FIELD( 15, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, sqrtA, ecc, 0),
    PB_FIELD( 16, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, omega0, sqrtA, 0),
    PB_FIELD( 17, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, i0, omega0, 0),
    PB_FIELD( 18, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, w, i0, 0),
    PB_FIELD( 19, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, omega_dot, w, 0),
    PB_FIELD( 20, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, idot, omega_dot, 0),
    PB_FIELD( 21, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, cuc, idot, 0),
    PB_FIELD( 22, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, cus, cuc, 0),
    PB_FIELD( 23, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, crc, cus, 0),
    PB_FIELD( 24, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, crs, crc, 0),
    PB_FIELD( 25, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, cic, crs, 0),
    PB_FIELD( 26, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, cis, cic, 0),
    PB_FIELD( 27, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, tgd, cis, 0),
    PB_FIELD( 28, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, tgd2, tgd, 0),
    PB_FIELD( 29, FLOAT   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, af0, tgd2, 0),
    PB_FIELD( 30, FLOAT   , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, af1, af0, 0),
    PB_FIELD( 31, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, af2, af1, 0),
    PB_FIELD( 32, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, axis, af2, 0),
    PB_FIELD( 33, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, n, axis, 0),
    PB_FIELD( 34, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, root_ecc, n, 0),
    PB_FIELD( 35, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, omega_t, root_ecc, 0),
    PB_FIELD( 36, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, omega_delta, omega_t, 0),
    PB_FIELD( 37, DOUBLE  , SINGULAR, STATIC  , OTHER, GPS_EPHEMERIS, Ek, omega_delta, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(List_GPS_EPHEMERIS, items[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_List_GPS_EPHEMERIS_GPS_EPHEMERIS)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(List_GPS_EPHEMERIS, items[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_List_GPS_EPHEMERIS_GPS_EPHEMERIS)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
