# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eph/eph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eph/eph.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\reph/eph.proto\"3\n\x12List_GPS_EPHEMERIS\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.GPS_EPHEMERIS\"\x8a\x04\n\rGPS_EPHEMERIS\x12\x0c\n\x04iodc\x18\x01 \x01(\x05\x12\r\n\x05iode2\x18\x03 \x01(\x05\x12\r\n\x05iode3\x18\x04 \x01(\x05\x12\x0b\n\x03ura\x18\x05 \x01(\x05\x12\x0c\n\x04\x66lag\x18\x06 \x01(\x05\x12\x0e\n\x06health\x18\x07 \x01(\x05\x12\x0c\n\x04svid\x18\x08 \x01(\x05\x12\x0b\n\x03toe\x18\t \x01(\x05\x12\x0b\n\x03toc\x18\n \x01(\x05\x12\x0c\n\x04week\x18\x0b \x01(\x05\x12\n\n\x02M0\x18\x0c \x01(\x01\x12\x0f\n\x07\x64\x65lta_n\x18\r \x01(\x01\x12\x0b\n\x03\x65\x63\x63\x18\x0e \x01(\x01\x12\r\n\x05sqrtA\x18\x0f \x01(\x01\x12\x0e\n\x06omega0\x18\x10 \x01(\x01\x12\n\n\x02i0\x18\x11 \x01(\x01\x12\t\n\x01w\x18\x12 \x01(\x01\x12\x11\n\tomega_dot\x18\x13 \x01(\x01\x12\x0c\n\x04idot\x18\x14 \x01(\x01\x12\x0b\n\x03\x63uc\x18\x15 \x01(\x01\x12\x0b\n\x03\x63us\x18\x16 \x01(\x01\x12\x0b\n\x03\x63rc\x18\x17 \x01(\x01\x12\x0b\n\x03\x63rs\x18\x18 \x01(\x01\x12\x0b\n\x03\x63ic\x18\x19 \x01(\x01\x12\x0b\n\x03\x63is\x18\x1a \x01(\x01\x12\x0b\n\x03tgd\x18\x1b \x01(\x01\x12\x0c\n\x04tgd2\x18\x1c \x01(\x01\x12\x0b\n\x03\x61\x66\x30\x18\x1d \x01(\x02\x12\x0b\n\x03\x61\x66\x31\x18\x1e \x01(\x02\x12\x0b\n\x03\x61\x66\x32\x18\x1f \x01(\x01\x12\x0c\n\x04\x61xis\x18  \x01(\x01\x12\t\n\x01n\x18! \x01(\x01\x12\x10\n\x08root_ecc\x18\" \x01(\x01\x12\x0f\n\x07omega_t\x18# \x01(\x01\x12\x13\n\x0bomega_delta\x18$ \x01(\x01\x12\n\n\x02\x45k\x18% \x01(\x01\x62\x06proto3')
)




_LIST_GPS_EPHEMERIS = _descriptor.Descriptor(
  name='List_GPS_EPHEMERIS',
  full_name='List_GPS_EPHEMERIS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='List_GPS_EPHEMERIS.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=68,
)


_GPS_EPHEMERIS = _descriptor.Descriptor(
  name='GPS_EPHEMERIS',
  full_name='GPS_EPHEMERIS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iodc', full_name='GPS_EPHEMERIS.iodc', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iode2', full_name='GPS_EPHEMERIS.iode2', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iode3', full_name='GPS_EPHEMERIS.iode3', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ura', full_name='GPS_EPHEMERIS.ura', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='GPS_EPHEMERIS.flag', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='health', full_name='GPS_EPHEMERIS.health', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='svid', full_name='GPS_EPHEMERIS.svid', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toe', full_name='GPS_EPHEMERIS.toe', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toc', full_name='GPS_EPHEMERIS.toc', index=8,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='week', full_name='GPS_EPHEMERIS.week', index=9,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='M0', full_name='GPS_EPHEMERIS.M0', index=10,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta_n', full_name='GPS_EPHEMERIS.delta_n', index=11,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecc', full_name='GPS_EPHEMERIS.ecc', index=12,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sqrtA', full_name='GPS_EPHEMERIS.sqrtA', index=13,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omega0', full_name='GPS_EPHEMERIS.omega0', index=14,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i0', full_name='GPS_EPHEMERIS.i0', index=15,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='GPS_EPHEMERIS.w', index=16,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omega_dot', full_name='GPS_EPHEMERIS.omega_dot', index=17,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idot', full_name='GPS_EPHEMERIS.idot', index=18,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cuc', full_name='GPS_EPHEMERIS.cuc', index=19,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cus', full_name='GPS_EPHEMERIS.cus', index=20,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crc', full_name='GPS_EPHEMERIS.crc', index=21,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crs', full_name='GPS_EPHEMERIS.crs', index=22,
      number=24, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cic', full_name='GPS_EPHEMERIS.cic', index=23,
      number=25, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cis', full_name='GPS_EPHEMERIS.cis', index=24,
      number=26, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tgd', full_name='GPS_EPHEMERIS.tgd', index=25,
      number=27, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tgd2', full_name='GPS_EPHEMERIS.tgd2', index=26,
      number=28, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='af0', full_name='GPS_EPHEMERIS.af0', index=27,
      number=29, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='af1', full_name='GPS_EPHEMERIS.af1', index=28,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='af2', full_name='GPS_EPHEMERIS.af2', index=29,
      number=31, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='axis', full_name='GPS_EPHEMERIS.axis', index=30,
      number=32, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n', full_name='GPS_EPHEMERIS.n', index=31,
      number=33, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root_ecc', full_name='GPS_EPHEMERIS.root_ecc', index=32,
      number=34, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omega_t', full_name='GPS_EPHEMERIS.omega_t', index=33,
      number=35, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omega_delta', full_name='GPS_EPHEMERIS.omega_delta', index=34,
      number=36, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ek', full_name='GPS_EPHEMERIS.Ek', index=35,
      number=37, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=593,
)

_LIST_GPS_EPHEMERIS.fields_by_name['items'].message_type = _GPS_EPHEMERIS
DESCRIPTOR.message_types_by_name['List_GPS_EPHEMERIS'] = _LIST_GPS_EPHEMERIS
DESCRIPTOR.message_types_by_name['GPS_EPHEMERIS'] = _GPS_EPHEMERIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

List_GPS_EPHEMERIS = _reflection.GeneratedProtocolMessageType('List_GPS_EPHEMERIS', (_message.Message,), dict(
  DESCRIPTOR = _LIST_GPS_EPHEMERIS,
  __module__ = 'eph.eph_pb2'
  # @@protoc_insertion_point(class_scope:List_GPS_EPHEMERIS)
  ))
_sym_db.RegisterMessage(List_GPS_EPHEMERIS)

GPS_EPHEMERIS = _reflection.GeneratedProtocolMessageType('GPS_EPHEMERIS', (_message.Message,), dict(
  DESCRIPTOR = _GPS_EPHEMERIS,
  __module__ = 'eph.eph_pb2'
  # @@protoc_insertion_point(class_scope:GPS_EPHEMERIS)
  ))
_sym_db.RegisterMessage(GPS_EPHEMERIS)


# @@protoc_insertion_point(module_scope)
