/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Sep 29 15:34:50 2017. */

#include "pos.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t List_PositioningReceiverInfo_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, List_PositioningReceiverInfo, items, items, &PositioningReceiverInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t PositioningReceiverInfo_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, PositioningReceiverInfo, pv, pv, &PositioningPosvel_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, PositioningReceiverInfo, lla, pv, &PositioningLatLonAlt_fields),
    PB_FIELD(  3, DOUBLE  , REPEATED, STATIC  , OTHER, PositioningReceiverInfo, receiver_time, lla, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningReceiverInfo, clock_drift, receiver_time, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningLatLonAlt_fields[4] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningLatLonAlt, lat, lat, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningLatLonAlt, lon, lat, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningLatLonAlt, alt, lon, 0),
    PB_LAST_FIELD
};

const pb_field_t PositioningPosvel_fields[7] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, PositioningPosvel, x, x, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosvel, y, x, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosvel, z, y, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosvel, vx, z, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosvel, vy, vx, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, PositioningPosvel, vz, vy, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(List_PositioningReceiverInfo, items[0]) < 65536 && pb_membersize(PositioningReceiverInfo, pv) < 65536 && pb_membersize(PositioningReceiverInfo, lla) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_List_PositioningReceiverInfo_PositioningReceiverInfo_PositioningLatLonAlt_PositioningPosvel)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(List_PositioningReceiverInfo, items[0]) < 256 && pb_membersize(PositioningReceiverInfo, pv) < 256 && pb_membersize(PositioningReceiverInfo, lla) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_List_PositioningReceiverInfo_PositioningReceiverInfo_PositioningLatLonAlt_PositioningPosvel)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
