# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eph/pos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eph/pos.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\reph/pos.proto\"G\n\x1cList_PositioningReceiverInfo\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.PositioningReceiverInfo\"\x8d\x01\n\x17PositioningReceiverInfo\x12\x1e\n\x02pv\x18\x01 \x01(\x0b\x32\x12.PositioningPosvel\x12\"\n\x03lla\x18\x02 \x01(\x0b\x32\x15.PositioningLatLonAlt\x12\x19\n\rreceiver_time\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x13\n\x0b\x63lock_drift\x18\x04 \x01(\x01\"=\n\x14PositioningLatLonAlt\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x01\"X\n\x11PositioningPosvel\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02vx\x18\x04 \x01(\x01\x12\n\n\x02vy\x18\x05 \x01(\x01\x12\n\n\x02vz\x18\x06 \x01(\x01\x62\x06proto3')
)




_LIST_POSITIONINGRECEIVERINFO = _descriptor.Descriptor(
  name='List_PositioningReceiverInfo',
  full_name='List_PositioningReceiverInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='List_PositioningReceiverInfo.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=88,
)


_POSITIONINGRECEIVERINFO = _descriptor.Descriptor(
  name='PositioningReceiverInfo',
  full_name='PositioningReceiverInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pv', full_name='PositioningReceiverInfo.pv', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lla', full_name='PositioningReceiverInfo.lla', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receiver_time', full_name='PositioningReceiverInfo.receiver_time', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='clock_drift', full_name='PositioningReceiverInfo.clock_drift', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=232,
)


_POSITIONINGLATLONALT = _descriptor.Descriptor(
  name='PositioningLatLonAlt',
  full_name='PositioningLatLonAlt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='PositioningLatLonAlt.lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='PositioningLatLonAlt.lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alt', full_name='PositioningLatLonAlt.alt', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=295,
)


_POSITIONINGPOSVEL = _descriptor.Descriptor(
  name='PositioningPosvel',
  full_name='PositioningPosvel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PositioningPosvel.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='PositioningPosvel.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='PositioningPosvel.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vx', full_name='PositioningPosvel.vx', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vy', full_name='PositioningPosvel.vy', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vz', full_name='PositioningPosvel.vz', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=385,
)

_LIST_POSITIONINGRECEIVERINFO.fields_by_name['items'].message_type = _POSITIONINGRECEIVERINFO
_POSITIONINGRECEIVERINFO.fields_by_name['pv'].message_type = _POSITIONINGPOSVEL
_POSITIONINGRECEIVERINFO.fields_by_name['lla'].message_type = _POSITIONINGLATLONALT
DESCRIPTOR.message_types_by_name['List_PositioningReceiverInfo'] = _LIST_POSITIONINGRECEIVERINFO
DESCRIPTOR.message_types_by_name['PositioningReceiverInfo'] = _POSITIONINGRECEIVERINFO
DESCRIPTOR.message_types_by_name['PositioningLatLonAlt'] = _POSITIONINGLATLONALT
DESCRIPTOR.message_types_by_name['PositioningPosvel'] = _POSITIONINGPOSVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

List_PositioningReceiverInfo = _reflection.GeneratedProtocolMessageType('List_PositioningReceiverInfo', (_message.Message,), dict(
  DESCRIPTOR = _LIST_POSITIONINGRECEIVERINFO,
  __module__ = 'eph.pos_pb2'
  # @@protoc_insertion_point(class_scope:List_PositioningReceiverInfo)
  ))
_sym_db.RegisterMessage(List_PositioningReceiverInfo)

PositioningReceiverInfo = _reflection.GeneratedProtocolMessageType('PositioningReceiverInfo', (_message.Message,), dict(
  DESCRIPTOR = _POSITIONINGRECEIVERINFO,
  __module__ = 'eph.pos_pb2'
  # @@protoc_insertion_point(class_scope:PositioningReceiverInfo)
  ))
_sym_db.RegisterMessage(PositioningReceiverInfo)

PositioningLatLonAlt = _reflection.GeneratedProtocolMessageType('PositioningLatLonAlt', (_message.Message,), dict(
  DESCRIPTOR = _POSITIONINGLATLONALT,
  __module__ = 'eph.pos_pb2'
  # @@protoc_insertion_point(class_scope:PositioningLatLonAlt)
  ))
_sym_db.RegisterMessage(PositioningLatLonAlt)

PositioningPosvel = _reflection.GeneratedProtocolMessageType('PositioningPosvel', (_message.Message,), dict(
  DESCRIPTOR = _POSITIONINGPOSVEL,
  __module__ = 'eph.pos_pb2'
  # @@protoc_insertion_point(class_scope:PositioningPosvel)
  ))
_sym_db.RegisterMessage(PositioningPosvel)


_POSITIONINGRECEIVERINFO.fields_by_name['receiver_time'].has_options = True
_POSITIONINGRECEIVERINFO.fields_by_name['receiver_time']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
